export function deleteAccountPage(options: {
  nonce: string;
  error?: string;
  success?: boolean;
  username?: string;
}): string {
  const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
  const eye = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.7"/></svg>';
  const eyeOff = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m3 3 18 18"/><path d="M10.6 6.1A10.7 10.7 0 0 1 12 6c6 0 9.5 6 9.5 6a18.7 18.7 0 0 1-3 3.7"/><path d="M6.2 6.2C3.9 7.8 2.5 12 2.5 12s3.5 6 9.5 6a9.8 9.8 0 0 0 3-.5"/><path d="M9.9 9.9a3 3 0 0 0 4.2 4.2"/></svg>';
  const error = options.error?.trim() ?? '';
  const username = options.username?.trim() ?? '';
  const success = options.success === true;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="robots" content="noindex,nofollow"><title>Yutaka · Delete account</title>
<style nonce="${options.nonce}">
:root{color-scheme:light;--bg:#F6F9F6;--surface:#FFFFFF;--raised:#F3F8F4;--line:#D9E7DE;--text:#0F1216;--muted:#66736C;--accent:#00BD91;--danger:#D83A4E;--danger-bg:#FFF1F3;--shadow:0 16px 48px rgba(15,18,22,.08)}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#0F1216;--surface:#13181D;--raised:#192126;--line:#272F35;--text:#F0F2F3;--muted:#ADB5BB;--accent:#27C6A0;--danger:#FF5353;--danger-bg:rgba(255,83,83,.10);--shadow:0 18px 54px rgba(0,0,0,.30)}}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);font:15px/1.5 Inter,"Segoe UI",Roboto,"Noto Sans","Helvetica Neue",Arial,system-ui,sans-serif;display:grid;place-items:center;padding:24px}.shell{width:min(100%,620px)}.brand{display:flex;align-items:center;gap:12px;margin-bottom:18px}.mark{display:grid;place-items:center;width:46px;height:46px;border-radius:16px;background:linear-gradient(145deg,#0F9F70,#00BD91);font-size:26px;font-weight:950;color:#053A28}.brand strong{display:block;font-size:22px;line-height:1.05;letter-spacing:-.7px}.brand span{color:var(--muted);font-size:12px;font-weight:700}.card{background:var(--surface);border:1px solid var(--line);border-radius:24px;box-shadow:var(--shadow);padding:26px}.danger-icon{width:52px;height:52px;border-radius:18px;background:var(--danger-bg);color:var(--danger);display:grid;place-items:center;font-size:26px;margin-bottom:18px}h1{font-size:30px;line-height:1.15;letter-spacing:-1px;margin:0 0 8px}p{margin:0;color:var(--muted)}.notice{margin:18px 0;padding:14px 16px;border:1px solid var(--line);border-radius:16px;background:var(--raised);color:var(--text)}.notice strong{display:block;margin-bottom:4px}.error{margin:16px 0;padding:12px 14px;border-radius:14px;background:var(--danger-bg);color:var(--danger);font-weight:750}.success{margin:18px 0;padding:14px 16px;border-radius:16px;border:1px solid color-mix(in srgb,var(--accent),var(--line) 60%);background:color-mix(in srgb,var(--accent),transparent 90%);color:var(--text)}form{display:grid;gap:14px;margin-top:20px}label{display:grid;gap:7px;font-weight:800}input{width:100%;min-height:50px;border:1px solid var(--line);border-radius:14px;background:var(--raised);color:var(--text);padding:12px 14px;font:inherit;outline:none}input:focus{border-color:var(--accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent),transparent 78%)}.password-field{position:relative}.password-field input{padding-right:58px}.password-toggle{position:absolute;right:5px;top:50%;transform:translateY(-50%);width:40px;height:40px;min-height:40px;border:0;border-radius:11px;padding:0;margin:0;background:transparent;color:var(--muted);display:grid;place-items:center}.password-toggle:hover{background:var(--surface);color:var(--accent);filter:none}.password-toggle svg{width:20px;height:20px;pointer-events:none}.password-toggle [hidden]{display:none}small{color:var(--muted);font-weight:600}button{min-height:50px;border:0;border-radius:14px;padding:12px 16px;font:inherit;font-weight:850;cursor:pointer;background:var(--danger);color:#fff;margin-top:4px}button:hover{filter:brightness(1.04)}a{color:var(--accent);font-weight:800}.footer{margin-top:16px;text-align:center;color:var(--muted);font-size:12px}
</style></head><body><main class="shell"><div class="brand"><div class="mark">K</div><div><strong>Yutaka</strong><span>Self-hosted account deletion</span></div></div><section class="card"><div class="danger-icon">×</div><h1>${success ? 'Account deleted' : 'Delete your Yutaka account'}</h1>
${success ? `<div class="success"><strong>${username ? escape(username) : 'Your account'}</strong> and its Worker-side data were permanently deleted.</div><p>Local copies already stored on your devices and files you previously exported to services such as Telegram or Google Drive are not erased by this web action.</p>` : `<p>Use this page when you no longer have Yutaka installed or prefer to delete your self-hosted sync account from a browser.</p><div class="notice"><strong>This permanently removes Worker-side account data.</strong>Synchronized finance data, profile media, device/session records, backup schedules, and stored Telegram/Google Drive credentials for this account are deleted. Local copies on devices and files already exported to external services are not automatically removed.</div>${error ? `<div class="error" role="alert">${escape(error)}</div>` : ''}<form method="post" action="/delete-account" autocomplete="off"><label>Username<input name="username" value="${escape(username)}" autocomplete="username" required minlength="3" maxlength="32" autocapitalize="none" spellcheck="false"></label><label for="delete-password">Password</label><div class="password-field"><input id="delete-password" type="password" name="password" autocomplete="current-password" required minlength="8" maxlength="256"><button type="button" class="password-toggle" id="password-toggle" aria-controls="delete-password" aria-label="Show password" aria-pressed="false" title="Show password"><span data-eye="show">${eye}</span><span data-eye="hide" hidden>${eyeOff}</span></button></div><label>Type DELETE to confirm<input name="confirmation" autocomplete="off" required pattern="DELETE" maxlength="6" autocapitalize="characters" spellcheck="false"></label><small>This action cannot be undone. If this is the final account on the Worker, first-user registration becomes available again.</small><button type="submit">Permanently delete account</button></form>`}
</section><div class="footer">Yutaka · self-hosted sync</div></main><script nonce="${options.nonce}">const toggle=document.getElementById('password-toggle');const input=document.getElementById('delete-password');if(toggle&&input){toggle.addEventListener('click',()=>{const visible=input.type==='password';input.type=visible?'text':'password';toggle.setAttribute('aria-label',visible?'Hide password':'Show password');toggle.setAttribute('title',visible?'Hide password':'Show password');toggle.setAttribute('aria-pressed',String(visible));toggle.querySelector('[data-eye=show]').hidden=visible;toggle.querySelector('[data-eye=hide]').hidden=!visible;input.focus({preventScroll:true});});}</script></body></html>`;
}
